# Generated by Django 4.1.1 on 2023-03-11 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='current_datetime',
            field=models.DateField(default=datetime.datetime(2023, 3, 11, 21, 6, 40, 228607, tzinfo=datetime.timezone.utc)),
        ),
    ]
