# Generated by Django 4.1.1 on 2023-03-11 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_subscribe_current_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='current_datetime',
        ),
    ]
