# Generated by Django 4.1.1 on 2023-03-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_blog_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name1',
        ),
    ]
