# Generated by Django 4.1.1 on 2023-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_author_name1'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='events/')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
