# Generated by Django 4.1.1 on 2023-03-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_events_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
