# Generated by Django 4.1.1 on 2023-04-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=3000),
        ),
    ]
