# Generated by Django 4.1.1 on 2023-04-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_delete_events_remove_issuebook_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booktitle',
            field=models.CharField(max_length=100),
        ),
    ]
