# Generated by Django 4.1.1 on 2023-05-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_ordernow_issuebook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Returned', 'Returned')], default='Issued', max_length=100),
        ),
    ]
