# Generated by Django 4.0 on 2023-05-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_ordernow_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernow',
            name='userid',
        ),
        migrations.AddField(
            model_name='ordernow',
            name='issueid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.issuebook'),
        ),
    ]
